[package]
name = "web"
version = "0.1.0"
authors = ["Ruidy <r.nemausat@empfohlen.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
serde = "1.0.118"
env_logger = "0.8.2"